### ISSUE TITLE
User popup card

### ISSUE THREAD

**Issue by pumpkinlink** [jbw91/fix-twitter-ui#1]
when you hover the mouse over a username, there is a a pop up showing a quick view of their profile, the avatar inside that popup is still round [(screenshot)](https://imgur.com/a/Zs4iT7A), I think the corresponding class is `ProfileCard-avatarImage` but I'm not sure

**Comment by pumpkinlink** [comment]
Fixed it and created a [PR](https://github.com/jbw91/fix-twitter-ui/pull/2)

**Comment by johnbwoodruff** [comment]
Closed with #2.

**Comment by johnbwoodruff** [comment]
@pumpkinlink Your changes are now live as v1.0.3! Your extension should auto-update, or you can force the update. Thanks a bunch for the contribution!
